### PR TITLE
 fix: fix data race in schema merging logic by creating a copy instead of modifying the original struct instance

### LINKED ISSUE #395: Data Race when merging block schema body extensions
The refactoring work uncovered some data races when merging block schema body extensions.

```
❯ go test -cover -covermode=atomic -timeout=5m -race ./internal/langserver/handlers/
2024/06/03 12:09:47 tick at 2024-06-03 12:09:47.516536 +0200 CEST m=+0.134430399
==================
WARNING: DATA RACE
Read at 0x00c0085e37b8 by goroutine 1494:
  github.com/hashicorp/hcl-lang/decoder/internal/schemahelper.MergeBlockBodySchemas()
      /Users/dbanck/Projects/hcl-lang/decoder/internal/schemahelper/block_schema.go:43 +0xbaa
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).referenceOriginsInBody()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_origins.go:189 +0x198e
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CollectReferenceOrigins()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_origins.go:81 +0x2d9
  github.com/hashicorp/terraform-ls/internal/features/modules/jobs.DecodeReferenceOrigins()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/jobs/references.go:111 +0x34d
  github.com/hashicorp/terraform-ls/internal/features/modules.(*ModulesFeature).decodeModule.func3.3()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/events.go:297 +0x97
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:95 +0x72c
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start.gowrap1()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:57 +0x4f

Previous write at 0x00c0085e37b8 by goroutine 1495:
  github.com/hashicorp/hcl-lang/decoder/internal/schemahelper.MergeBlockBodySchemas()
      /Users/dbanck/Projects/hcl-lang/decoder/internal/schemahelper/block_schema.go:44 +0xc2d
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).decodeReferenceTargetsForBody()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_targets.go:143 +0x10a4
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CollectReferenceTargets()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_targets.go:98 +0x270
  github.com/hashicorp/terraform-ls/internal/features/modules/jobs.DecodeReferenceTargets()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/jobs/references.go:59 +0x34d
  github.com/hashicorp/terraform-ls/internal/features/modules.(*ModulesFeature).decodeModule.func3.2()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/events.go:283 +0x97
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:95 +0x72c
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start.gowrap1()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:57 +0x4f

==================
WARNING: DATA RACE
Write at 0x00c003bc193e by goroutine 1494:
  github.com/hashicorp/hcl-lang/decoder/internal/schemahelper.MergeBlockBodySchemas()
      /Users/dbanck/Projects/hcl-lang/decoder/internal/schemahelper/block_schema.go:46 +0xcce
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).referenceOriginsInBody()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_origins.go:189 +0x198e
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CollectReferenceOrigins()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_origins.go:81 +0x2d9
  github.com/hashicorp/terraform-ls/internal/features/modules/jobs.DecodeReferenceOrigins()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/jobs/references.go:111 +0x34d
  github.com/hashicorp/terraform-ls/internal/features/modules.(*ModulesFeature).decodeModule.func3.3()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/events.go:297 +0x97
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:95 +0x72c
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start.gowrap1()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:57 +0x4f

Previous write at 0x00c003bc193e by goroutine 1495:
  github.com/hashicorp/hcl-lang/decoder/internal/schemahelper.MergeBlockBodySchemas()
      /Users/dbanck/Projects/hcl-lang/decoder/internal/schemahelper/block_schema.go:46 +0xcce
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).decodeReferenceTargetsForBody()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_targets.go:143 +0x10a4
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CollectReferenceTargets()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_targets.go:98 +0x270
  github.com/hashicorp/terraform-ls/internal/features/modules/jobs.DecodeReferenceTargets()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/jobs/references.go:59 +0x34d
  github.com/hashicorp/terraform-ls/internal/features/modules.(*ModulesFeature).decodeModule.func3.2()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/events.go:283 +0x97
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:95 +0x72c
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start.gowrap1()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:57 +0x4f

==================
WARNING: DATA RACE
Write at 0x00c003bc196e by goroutine 1494:
  github.com/hashicorp/hcl-lang/decoder/internal/schemahelper.MergeBlockBodySchemas()
      /Users/dbanck/Projects/hcl-lang/decoder/internal/schemahelper/block_schema.go:46 +0xcce
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).referenceOriginsInBody()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_origins.go:189 +0x198e
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CollectReferenceOrigins()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_origins.go:81 +0x2d9
  github.com/hashicorp/terraform-ls/internal/features/modules/jobs.DecodeReferenceOrigins()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/jobs/references.go:111 +0x34d
  github.com/hashicorp/terraform-ls/internal/features/modules.(*ModulesFeature).decodeModule.func3.3()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/events.go:297 +0x97
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:95 +0x72c
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start.gowrap1()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:57 +0x4f

Previous read at 0x00c003bc196e by goroutine 1495:
  github.com/hashicorp/hcl-lang/schema.(*BodyExtensions).Copy()
      /Users/dbanck/Projects/hcl-lang/schema/body_schema.go:71 +0x465
  github.com/hashicorp/hcl-lang/schema.(*BodySchema).Copy()
      /Users/dbanck/Projects/hcl-lang/schema/body_schema.go:205 +0x360
  github.com/hashicorp/hcl-lang/decoder/internal/schemahelper.buildDynamicBlockSchema()
      /Users/dbanck/Projects/hcl-lang/decoder/internal/schemahelper/dynamic_block.go:25 +0x284
  github.com/hashicorp/hcl-lang/decoder/internal/schemahelper.MergeBlockBodySchemas()
      /Users/dbanck/Projects/hcl-lang/decoder/internal/schemahelper/block_schema.go:57 +0xe39
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).decodeReferenceTargetsForBody()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_targets.go:143 +0x10a4
  github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CollectReferenceTargets()
      /Users/dbanck/Projects/hcl-lang/decoder/reference_targets.go:98 +0x270
  github.com/hashicorp/terraform-ls/internal/features/modules/jobs.DecodeReferenceTargets()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/jobs/references.go:59 +0x34d
  github.com/hashicorp/terraform-ls/internal/features/modules.(*ModulesFeature).decodeModule.func3.2()
      /Users/dbanck/Projects/terraform-ls/internal/features/modules/events.go:283 +0x97
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:95 +0x72c
  github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start.gowrap1()
      /Users/dbanck/Projects/terraform-ls/internal/scheduler/scheduler.go:57 +0x4f
```

Creating a copy of the block before updating the extensions, fixes the race condition, but leads to test failures in hcl-lang:
https://github.com/hashicorp/hcl-lang/blob/9dbd8b963193f77e726c1620e8965c38e112a109/decoder/internal/schemahelper/block_schema.go#L42-L49

### Proposal

Investigate whether the fix to make a copy of the block uncovered another bug in the implementation regarding deeply nested dynamic blocks.

### PR DESCRIPTION
**Pull request by ansgarm**
Different jobs in terraform-ls use the same `hcl.Block` instance simultaneously and the schema merger modified it in the past.
We fixed this by creating a copy first which uncovered another bug: The `buildDynamicBlockSchema` function implicitly read that change from the dependent schema, which we fixed by reading from the `mergedSchema` instead. This in turn required us to also pass the dependent schema into the function as the `mergedSchema` also contains the static `lifecycle` block which can't be set via a dynamic block. This means we now iterate over all blocks in the dependent schema but copy their bodies from the `mergedSchema`.

Fixes #395

### CODE REVIEW

File: decoder/internal/schemahelper/block_schema.go [hunk 1]
```diff
@@ -38,23 +38,24 @@ func MergeBlockBodySchemas(block *hcl.Block, blockSchema *schema.BlockSchema) (*
...
-						block.Body.Extensions = &schema.BodyExtensions{}
+					if b.Body.Extensions == nil {
+						b.Body.Extensions = &schema.BodyExtensions{}
 					}
-					block.Body.Extensions.DynamicBlocks = true
+					b.Body.Extensions.DynamicBlocks = true
 				}
 
-				mergedSchema.Blocks[bType] = block
+				mergedSchema.Blocks[bType] = b
```
Comment (jpogran) [inline decoder/internal/schemahelper/block_schema.go:50]: Could we be a little more descriptive in variable names? I know it's against convention to have more than one character variables, but IMHO it improves readability here as `b` and `block` look so similar in meaning at a glance

**Review by jpogran — CHANGES_REQUESTED** [review]

File: decoder/internal/schemahelper/block_schema.go (hunk 1 above)
Comment (ansgarm) [reply decoder/internal/schemahelper/block_schema.go]: Renamed it to `copiedBlock` as per our offline discussion ✅

**Review by jpogran — APPROVED** [review]
Especially appreciate the doc comments on the `buildDynamicBlockSchema` func
